### ISSUE TITLE
Frontend change missing for CSRF token

### ISSUE THREAD

**Issue by huncrys** [drkno/PlexSSOv2#12]
First of all, thanks for this useful tool :)

As I see, 5a920a29b37a40c86d499ad33fdd6e5851002adb added CSRF token validation to the backend, but the UI never sends it, so it results in a validation error:

```
plexsso         | warn: PlexSSO.Service.Auth.AuthenticationValidator[0]
plexsso         |       Some properties which should not be null/empty were null/empty.
plexsso         |       Did you forget to add a header in your reverse proxy?
```

I've built an image with 31d255cb864fa079dfa2abe08a20c8ad668aa87e and it works.

Could you push these changes as well @drkno ?

**Comment by drkno** [comment]
The latest docker image should have the missing csrf/xsrf changes.
